### ISSUE TITLE
Groovy script to configure CAS

### ISSUE THREAD

**Issue by db0** [jenkinsci/cas-plugin#11]
This is a bit of an support request, but I'm hoping you could assist.

At the moment,in another Jenkins instance I'm using a groovy script similar to  [this](https://gist.github.com/zouzias/bf447ab020955ac70db5db5521c3d5b9) to configure LDAP authentication. I was wondering if you could provide something similar for configuring CAS as well. 

If not, no worries, I'll make-do with inserting the XML directly into the jenkins config, but I think a groovy script would be more appropriate.

Thanks in advance

**Comment by fcrespel** [comment]
I've never tried configuring Jenkins with a Groovy script, but judging by the example you linked to, you should be able to create a `new CasSecurityRealm(params...)` instead of the `LDAPSecurityRealm`. Refer to the [CasSecurityRealm.java](https://github.com/jenkinsci/cas-plugin/blob/master/src/main/java/org/jenkinsci/plugins/cas/CasSecurityRealm.java#L85) file and protocols (e.g. [Cas30Protocol.java](https://github.com/jenkinsci/cas-plugin/blob/master/src/main/java/org/jenkinsci/plugins/cas/protocols/Cas30Protocol.java#L44) to see which parameters to use.

**Comment by db0** [comment]
Perfect. That will help. I didnt know what to look for. I should be able to figure the rest on my own. Thanks!
